# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - reference
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

linters:
  enable:
    - errcheck      # Check for unchecked errors (enabled by default)
    - govet         # Vet examines Go source code (enabled by default)
    - ineffassign   # Detect ineffectual assignments (enabled by default)
    - staticcheck   # Static analysis (enabled by default)
    - unused        # Check for unused code (enabled by default)
    - misspell      # Find commonly misspelled words
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary conversions
    - unparam       # Find unused function parameters
    - gosec         # Security issues
    - gocritic      # Comprehensive Go linter
    - errorlint     # Find code that will cause problems with error wrapping
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending http request without context.Context

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104 # Audit errors not checked - covered by errcheck
      - G306 # Poor file permissions - often intentional in test files

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unused
        - unparam
        - gocyclo
        - dupl

    # Exclude error checks in example files
    - path: examples/
      linters:
        - errcheck
        - gosec
        - noctx

    # Exclude config package from some checks (generated parser and complex config logic)
    - path: config/
      linters:
        - gocyclo
        - gocritic
        - gosec
        - errcheck
        - noctx
        - errorlint
        - unparam
        - staticcheck

    # Allow file operations in main packages
    - path: submit.*\.go
      linters:
        - gosec
        - gocyclo
        - unparam
        - gocritic

    # Defer Close() calls don't need error check in most cases
    - text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck

    # os.Setenv/Unsetenv in tests don't need error check
    - text: "Error return value of.*os\\.(Setenv|Unsetenv|Chdir|RemoveAll)"
      linters:
        - errcheck

    # ClassAd.Set() errors are often not critical
    - text: "Error return value of.*ad\\.Set"
      linters:
        - errcheck

    # Allow unused ctx parameters (interfaces may require them)
    - text: "unused-parameter.*ctx"
      linters:
        - revive

    # Allow some variable naming conventions
    - text: "var-naming.*should be"
      linters:
        - revive

    # Allow some legacy naming (e.g., ConfigOptions)
    - text: "stutters"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0
