# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: '2'

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors (enabled by default)
    - govet         # Vet examines Go source code (enabled by default)
    - ineffassign   # Detect ineffectual assignments (enabled by default)
    - staticcheck   # Static analysis (enabled by default)
    - unused        # Check for unused code (enabled by default)
    - misspell      # Find commonly misspelled words
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary conversions
    - unparam       # Find unused function parameters
    - gosec         # Security issues
    - gocritic      # Comprehensive Go linter
    - errorlint     # Find code that will cause problems with error wrapping
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending http request without context.Context

issues:

  max-issues-per-linter: 0
  max-same-issues: 0
