//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// ParamInfo represents a single parameter definition
type ParamInfo struct {
	Name         string
	Default      string
	Win32Default string
	Type         string
	Range        string
	Description  string
	Usage        string
	Tags         string
	Custom       string
	Restart      string
}

func main() {
	if err := generate(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func generate() error {
	// Read param_info.in from the param directory
	params, err := parseParamInfo("../param/param_info.in")
	if err != nil {
		return fmt.Errorf("failed to parse param_info.in: %w", err)
	}

	// Generate Go code in config directory
	out, err := os.Create("param_defaults.go")
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer out.Close()

	// Write header
	fmt.Fprintln(out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "package config")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// ParamDefault represents a default parameter value from param_info.in")
	fmt.Fprintln(out, "type ParamDefault struct {")
	fmt.Fprintln(out, "\tName         string")
	fmt.Fprintln(out, "\tDefault      string")
	fmt.Fprintln(out, "\tWin32Default string")
	fmt.Fprintln(out, "\tType         string")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// paramDefaults contains all default values from HTCondor param_info.in")
	fmt.Fprintln(out, "var paramDefaults = []ParamDefault{")

	for _, p := range params {
		if p.Default == "" && p.Win32Default == "" {
			continue // Skip params with no defaults
		}
		fmt.Fprintf(out, "\t{Name: %q, Default: %q, Win32Default: %q, Type: %q},\n",
			p.Name, p.Default, p.Win32Default, p.Type)
	}

	fmt.Fprintln(out, "}")

	fmt.Printf("Generated param_defaults.go with %d parameters\n", len(params))
	return nil
}

func parseParamInfo(filename string) ([]ParamInfo, error) {
	file, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var params []ParamInfo
	var current *ParamInfo
	var heredocTag string
	var heredocLines []string

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		// Skip comments and empty lines
		if strings.HasPrefix(line, "##") || strings.TrimSpace(line) == "" {
			continue
		}

		// Check for param declaration [PARAM_NAME]
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			// Save previous param
			if current != nil {
				params = append(params, *current)
			}

			// Start new param
			name := strings.TrimPrefix(line, "[")
			name = strings.TrimSuffix(name, "]")
			current = &ParamInfo{
				Name: name,
				Type: "string", // default type
			}
			heredocTag = ""
			heredocLines = nil
			continue
		}

		if current == nil {
			continue
		}

		// Handle heredoc content
		if heredocTag != "" {
			if strings.TrimSpace(line) == heredocTag {
				// End of heredoc
				current.Default = strings.Join(heredocLines, "\n")
				heredocTag = ""
				heredocLines = nil
			} else {
				heredocLines = append(heredocLines, line)
			}
			continue
		}

		// Parse key=value or key: @tag
		if idx := strings.Index(line, "="); idx > 0 {
			key := strings.TrimSpace(line[:idx])
			value := strings.TrimSpace(line[idx+1:])
			setParamField(current, key, value)
		} else if idx := strings.Index(line, ": @"); idx > 0 {
			key := strings.TrimSpace(line[:idx])
			tag := strings.TrimSpace(line[idx+2:])
			// The field will be set when we finish reading the heredoc
			if key == "default" {
				heredocTag = tag
				heredocLines = []string{}
			}
		}
	}

	// Save last param
	if current != nil {
		params = append(params, *current)
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return params, nil
}

func setParamField(p *ParamInfo, key, value string) {
	switch key {
	case "default":
		p.Default = value
	case "win32_default":
		p.Win32Default = value
	case "type":
		p.Type = value
	case "range":
		p.Range = value
	case "description":
		p.Description = value
	case "usage":
		p.Usage = value
	case "tags", "tag":
		p.Tags = value
	case "customization":
		p.Custom = value
	case "restart":
		p.Restart = value
	}
}
